#!/bin/tcsh
#PBS -N asg:geobnds
#PBS -l nodes=8:c18c:ppn=16
#PBS -l walltime=24:00:00
#PBS -j oe

mpirun -mca orte_base_help_aggregate 0 --mca mpi_warn_on_fork 0 --map-by node -np 128 python-mpi /sciclone/aiddata10/REU/geoboundaries/gb.py
